name: portfolio_felipe_2025
description: "Portfólio Felipe.R DEV"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  akar_icons_flutter: ^1.1.21
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: GasoekOne
      fonts:
        - asset: assets/fonts/Gasoek_One/GasoekOne-Regular.ttf
    - family: Gantari
      fonts:
        - asset: assets/fonts/Gantari/Gantari-VariableFont_wght.ttf
